# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/msm8974-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter cancro virgo,$(TARGET_DEVICE)),)

endif
